name: Publish NPM Package

on:
  release:
    types: [created]

concurrency:
  group: package
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish UI to NPM package
        run: npm publish ./ui
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
